import { Static } from 'ivue/extras';

// invariant: Design tokens are the only source of colour and timing (tools/invariant-field-v2/invariant-field.invariants.md)
class $DesignTokens {
  static get VALUES() {
    return Object.freeze({
      'color-background': '#06080c',
      'color-background-glow': '#0d131c',
      'color-panel': '#0d131c',
      'color-panel-raised': '#111a26',
      'color-panel-active': '#162131',
      'color-field': '#06080c',
      'color-border': '#293a50',
      'color-border-strong': '#405a78',
      'color-foreground': '#aec0d4',
      'color-foreground-components': '174 192 212',
      'color-foreground-strong': '#eaf1fa',
      'color-muted': '#7f93aa',
      'color-muted-dark': '#526276',
      'color-accent': '#6de2ff',
      'color-accent-components': '109 226 255',
      'color-accent-soft': '#162131',
      'color-focus': '#6de2ff',
      'color-selection': '#b99cff',
      'color-success': '#5ee3b1',
      'color-warning': '#ffc76b',
      'color-rot': '#ff916b',
      'color-reality': '#ffd166',
      'color-reality-components': '255 209 102',
      'color-reality-absolute': '#f2e9ff',
      'color-reality-absolute-components': '242 233 255',
      'color-reality-renegotiable': '#77e4ff',
      'color-reality-renegotiable-components': '119 228 255',
      'color-chosen': '#bea7ff',
      'color-chosen-components': '190 167 255',
      'color-danger': '#ff657d',
      'color-white': '#eaf1fa',
      'color-panel-components': '13 19 28',
      'color-black-components': '0 0 0',
      'color-domain-system': '#63d8ff',
      'color-domain-state': '#79a7ff',
      'color-domain-interaction': '#aa91ff',
      'color-domain-language': '#e48eff',
      'color-domain-data': '#5ee3b1',
      'color-domain-process': '#a8e66b',
      'color-domain-evidence': '#ffd166',
      'color-domain-risk': '#ff916b',
      'color-field-grid': 'rgb(115 177 221 / 13%)',
      'color-field-axis': 'rgb(115 204 255 / 25%)',
      'color-selection-halo': 'rgb(185 156 255 / 24%)',
      'color-reality-halo': 'rgb(255 209 102 / 20%)',
      'color-alarm-halo': 'rgb(255 101 125 / 22%)',
      'font-family-sans':
        "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      'font-family-monospace':
        "'IBM Plex Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
      'font-size-micro': '0.625rem',
      'font-size-caption': '0.6875rem',
      'font-size-label': '0.6875rem',
      'font-size-compact': '0.75rem',
      'font-size-detail': '0.75rem',
      'font-size-small': '0.8125rem',
      'font-size-supporting': '0.8125rem',
      'font-size-caption-body': '0.8125rem',
      'font-size-body': '0.875rem',
      'font-size-base': '1rem',
      'font-size-lede': '0.875rem',
      'font-size-heading': '1.25rem',
      'font-size-display': '2rem',
      'font-size-field-label': '0.625rem',
      'font-size-reality-label': '1.125rem',
      'font-weight-medium': '520',
      'font-weight-semibold': '640',
      'font-weight-bold': '720',
      'font-weight-heavy': '720',
      'letter-spacing-display': '-0.035em',
      'letter-spacing-eyebrow': '0.12em',
      'letter-spacing-field-label': '0.01em',
      'line-height-compact': '1.15',
      'line-height-readable': '1.6',
      'line-height-relaxed': '1.6',
      'space-none': '0',
      'space-1-pixel': '1px',
      'space-2-pixels': '2px',
      'space-3-pixels': '3px',
      'space-4-pixels': '4px',
      'space-5-pixels': '5px',
      'space-6-pixels': '6px',
      'space-7-pixels': '7px',
      'space-8-pixels': '8px',
      'space-9-pixels': '9px',
      'space-10-pixels': '10px',
      'space-11-pixels': '11px',
      'space-12-pixels': '12px',
      'space-13-pixels': '13px',
      'space-14-pixels': '14px',
      'space-15-pixels': '15px',
      'space-16-pixels': '16px',
      'space-18-pixels': '18px',
      'space-20-pixels': '20px',
      'space-22-pixels': '22px',
      'space-28-pixels': '28px',
      'space-42-pixels': '42px',
      'space-50-pixels': '50px',
      'space-93-pixels': '93px',
      'space-one-rem': '1rem',
      'space-two-rem': '2rem',
      'radius-small': '4px',
      'radius-badge': '5px',
      'radius-dot': '999px',
      'radius-control': '0.375rem',
      'radius-card': '0.625rem',
      'radius-panel': '0.875rem',
      'ease-standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
      'ease-enter': 'cubic-bezier(0, 0, 0.2, 1)',
      'ease-exit': 'cubic-bezier(0.4, 0, 1, 1)',
      'ease-focus-flight': 'cubic-bezier(0.16, 1, 0.3, 1)',
      'ease-confirm': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      'duration-input-feedback': '70ms',
      'duration-hover-feedback': '90ms',
      'duration-selection-confirm': '140ms',
      'duration-chrome-transition': '180ms',
      'duration-focus-flight': '520ms',
      'duration-snapshot-morph': '640ms',
      'duration-record-birth': '420ms',
      'duration-record-rot': '520ms',
      'duration-trace-decay': '900ms',
    });
  }

  static stylesheet(): string {
    const declarations = Object.entries(this.VALUES)
      .map(([tokenName, tokenValue]) => `  --${tokenName}: ${tokenValue};`)
      .join('\n');
    return `:root {\n  color-scheme: dark;\n${declarations}\n}\n`;
  }
}

export namespace DesignTokens {
  export const $Class = Static($DesignTokens);
  export let Class = $Class;
}
