import { Static } from 'ivue/extras';
import { Reactive } from 'ivue';
import { ref, shallowRef } from 'vue';
import {
  MarkdownDocument,
  type MarkdownDocumentOptions,
  type MarkdownSource,
} from './MarkdownDocument';
import type {
  BlockRecord,
  BlockKind,
  TableCellRecord,
  TableColumnAlignment,
} from './MarkdownParser';
import { TextCoordinates } from '../text/TextCoordinates';
import {
  WrapBreakOpportunity,
  type WrapBreakProfile,
} from '../text/WrapBreakOpportunity';
import { StatusChannel } from '../system/StatusChannel';
import type { TableBorderGlyphSet } from '../theme/ThemeIcons';
import {
  MarkdownStylesheet,
  type MarkdownElementSelector,
} from './MarkdownStylesheet';
import { TextViewport } from '../text/TextViewport';

// invariant: Parsing starts only after opening (src/modules/markdown/markdown.invariants.md)
// invariant: Preview rendering follows visible rows (src/modules/markdown/markdown.invariants.md)
// invariant: Explicit jumps use one reading position (src/modules/text/text.invariants.md)
class $MarkdownPreview {
  protected static get $emptyBlocks(): readonly BlockRecord[] {
    const emptyBlocks: readonly BlockRecord[] = Object.freeze([]);
    return emptyBlocks;
  }

  declare $watchEffect: typeof import('vue').watchEffect;
  declare $stopEffects: () => void;

  protected renderTarget: RenderTarget | null = null;
  protected documentOptions: MarkdownDocumentOptions = {};

  get document() {
    return shallowRef<MarkdownDocument.Model | null>(null);
  }
  get active() {
    return ref(false);
  }
  get scrollTop() {
    return ref(0);
  }

  get blocks(): readonly BlockRecord[] {
    const previewClass = this.constructor as typeof $MarkdownPreview;
    return this.document.value?.blocks.value ?? previewClass.$emptyBlocks;
  }

  get parsedRevision(): number {
    return this.document.value?.revision.value ?? -1;
  }

  open(
    source: MarkdownSource,
    renderTarget: RenderTarget | null = null,
    documentOptions: MarkdownDocumentOptions = {},
  ): void {
    if (this.active.value) this.close();

    this.documentOptions = documentOptions;
    this.renderTarget = renderTarget;
    const document = this.createDocument(source);
    this.document.value = document;
    this.scrollTop.value = 0;
    this.active.value = true;
    document.open();
    this.$watchEffect(() => this.invalidateRender());
    StatusChannel.Class.update({
      markdownPreviewOpen: true,
      markdownScrollTop: 0,
    });
  }

  // invariant: Closing releases all preview work (src/modules/markdown/markdown.invariants.md)
  close(): void {
    const target = this.renderTarget;
    this.document.value?.close();
    this.document.value = null;
    this.active.value = false;
    this.scrollTop.value = 0;
    this.renderTarget = null;
    this.documentOptions = {};
    this.$stopEffects();
    target?.requestRender();
    StatusChannel.Class.update({
      markdownPreviewOpen: false,
      markdownScrollTop: 0,
      markdownBlockCount: 0,
    });
  }

  dispose(): void {
    this.close();
  }

  attachRenderTarget(target: RenderTarget): void {
    this.renderTarget = target;
    if (this.active.value) target.requestRender();
  }

  detachRenderTarget(target: RenderTarget): void {
    if (this.renderTarget === target) this.renderTarget = null;
  }

  scrollBy(delta: number, width: number, height: number): void {
    const maximum = Math.max(0, this.totalRows(width) - Math.max(1, height));
    this.scrollTop.value = Math.max(
      0,
      Math.min(maximum, this.scrollTop.value + delta),
    );
    StatusChannel.Class.update({ markdownScrollTop: this.scrollTop.value });
  }

  scrollTo(row: number, width: number, height: number): void {
    const maximum = Math.max(0, this.totalRows(width) - Math.max(1, height));
    this.scrollTop.value = Math.max(0, Math.min(maximum, row));
    StatusChannel.Class.update({ markdownScrollTop: this.scrollTop.value });
  }

  /** The first rendered row generated by the source block that contains `sourceLine`. */
  firstRenderedRowForSourceLine(
    sourceLine: number,
    width: number,
  ): number | null {
    const stylesheet = MarkdownStylesheet.Class;
    const rowWidth = Math.max(1, Math.floor(width));
    let rowIndex = 0;
    let previousSelector: MarkdownElementSelector | null = null;

    for (const block of this.blocks) {
      if (block.kind === 'list') continue;
      const selector = stylesheet.blockSelector(block);
      rowIndex += stylesheet.spacingBetween(previousSelector, selector);
      previousSelector = selector;
      if (
        sourceLine >= block.range.startLine &&
        sourceLine < block.range.endLine
      ) {
        return rowIndex;
      }
      rowIndex += this.rowCountForBlock(block, rowWidth);
    }
    return null;
  }

  /** Reveal the rendered block for a source jump at the shared reading position. */
  revealSourceLine(sourceLine: number, width: number, height: number): boolean {
    const targetRow = this.firstRenderedRowForSourceLine(sourceLine, width);
    if (targetRow === null) return false;
    const totalRows = this.totalRows(width);
    const nextScrollTop = TextViewport.Class.scrollTopForTarget(
      targetRow,
      this.scrollTop.value,
      height,
      totalRows,
      'reading',
    );
    this.scrollTo(nextScrollTop, width, height);
    return true;
  }

  // invariant: Preview rendering follows visible rows (src/modules/markdown/markdown.invariants.md)
  visibleRows(
    width: number,
    height: number,
    tableBorders: TableBorderGlyphSet,
  ): PreviewRow[] {
    const document = this.document.value;
    const rowWidth = Math.max(1, Math.floor(width));
    const rowLimit = Math.max(0, Math.floor(height));
    if (!document || rowLimit === 0) return [];

    if (document.error.value)
      return [this.statusRow(`Markdown: ${document.error.value}`)];
    if (document.parsing.value && document.blocks.value.length === 0) {
      return [this.statusRow('Parsing Markdown…')];
    }

    return this.collectRows(
      document.blocks.value,
      rowWidth,
      this.scrollTop.value,
      rowLimit,
      tableBorders,
    );
  }

  /** Materialize the rendered text only for operations whose domain is the whole preview (find and
   * copy selection). Normal painting continues to call visibleRows and stays viewport bounded. */
  allRows(width: number, tableBorders: TableBorderGlyphSet): PreviewRow[] {
    const document = this.document.value;
    const rowWidth = Math.max(1, Math.floor(width));
    if (!document) return [];
    if (document.error.value)
      return [this.statusRow(`Markdown: ${document.error.value}`)];
    if (document.parsing.value && document.blocks.value.length === 0) {
      return [this.statusRow('Parsing Markdown…')];
    }
    return this.collectRows(
      document.blocks.value,
      rowWidth,
      0,
      Number.MAX_SAFE_INTEGER,
      tableBorders,
    );
  }

  /** The exact plain text represented by one preview row, shared by rendering hit-tests, find, and
   * clipboard selection so those paths cannot disagree about cell-to-text mapping. */
  textForRow(row: PreviewRow): string {
    if (row.overrideText !== undefined) return row.overrideText;
    if (!row.block) return '';
    return `${row.prefix}${row.block.text.slice(row.textStart, row.textEnd)}${row.suffix}`;
  }

  // invariant: Markdown presentation resolves through one stylesheet (src/modules/markdown/markdown.invariants.md)
  totalRows(width: number): number {
    const document = this.document.value;
    if (!document) return 0;
    const stylesheet = MarkdownStylesheet.Class;
    let rowCount = 0;
    let previousSelector: MarkdownElementSelector | null = null;
    const rowWidth = Math.max(1, Math.floor(width));
    for (const block of document.blocks.value) {
      if (block.kind === 'list') continue;
      const selector = stylesheet.blockSelector(block);
      rowCount += stylesheet.spacingBetween(previousSelector, selector);
      rowCount += this.rowCountForBlock(block, rowWidth);
      previousSelector = selector;
    }
    if (previousSelector !== null) {
      rowCount += stylesheet.spacingBetween(previousSelector, null);
    }
    return rowCount;
  }

  protected createDocument(source: MarkdownSource): MarkdownDocument.Model {
    return new MarkdownDocument.Class(source, this.documentOptions);
  }

  protected invalidateRender(): void {
    void this.active.value;
    void this.scrollTop.value;
    const document = this.document.value;
    if (document) {
      void document.revision.value;
      void document.parsing.value;
      void document.error.value;
    }
    this.renderTarget?.requestRender();
  }

  protected collectRows(
    blocks: readonly BlockRecord[],
    width: number,
    firstVisible: number,
    visibleCount: number,
    tableBorders: TableBorderGlyphSet,
  ): PreviewRow[] {
    const stylesheet = MarkdownStylesheet.Class;
    const rows: PreviewRow[] = [];
    let rowIndex = 0;
    const endVisible = firstVisible + visibleCount;
    let previousSelector: MarkdownElementSelector | null = null;

    const pushSpacers = (spacerCount: number): void => {
      for (let spacerIndex = 0; spacerIndex < spacerCount; spacerIndex++) {
        if (rowIndex >= firstVisible && rowIndex < endVisible) {
          rows.push(this.spacerRow());
        }
        rowIndex++;
      }
    };

    for (let blockIndex = 0; blockIndex < blocks.length; blockIndex++) {
      const block = blocks[blockIndex]!;
      if (block.kind === 'list') continue;
      const selector = stylesheet.blockSelector(block);
      pushSpacers(stylesheet.spacingBetween(previousSelector, selector));
      previousSelector = selector;
      if (rowIndex >= endVisible) break;
      const blockRowCount = this.rowCountForBlock(block, width);
      const blockEndRow = rowIndex + blockRowCount;

      if (blockEndRow > firstVisible && rowIndex < endVisible) {
        if (block.kind === 'table') {
          this.appendVisibleTableRows(
            rows,
            block,
            blockIndex,
            width,
            Math.max(0, firstVisible - rowIndex),
            Math.min(blockRowCount, endVisible - rowIndex),
            tableBorders,
          );
        } else {
          let blockLocalRow = 0;
          const emit: EmitRow = (
            emittedBlock,
            emittedBlockIndex,
            textStart,
            textEnd,
            prefix,
            suffix,
            role,
            overrideText,
          ) => {
            const emittedRowIndex = rowIndex + blockLocalRow;
            if (
              emittedRowIndex >= firstVisible &&
              emittedRowIndex < endVisible
            ) {
              rows.push({
                block: emittedBlock,
                blockIndex: emittedBlockIndex,
                textStart,
                textEnd,
                prefix,
                suffix,
                role,
                overrideText,
              });
            }
            blockLocalRow++;
            return emittedRowIndex + 1 >= endVisible;
          };
          this.visitBlock(block, blockIndex, width, emit);
        }
      }

      rowIndex = blockEndRow;
      if (rowIndex >= endVisible) break;
    }
    if (previousSelector !== null && rowIndex < endVisible) {
      pushSpacers(stylesheet.spacingBetween(previousSelector, null));
    }
    return rows;
  }

  protected spacerRow(): PreviewRow {
    return {
      block: null,
      blockIndex: -1,
      textStart: 0,
      textEnd: 0,
      prefix: '',
      suffix: '',
      role: 'spacer',
    };
  }

  protected rowCountForBlock(block: BlockRecord, width: number): number {
    if (block.kind === 'table') return (block.table?.rows.length ?? 0) + 1;
    let rowCount = 0;
    this.visitBlock(block, -1, width, () => {
      rowCount++;
      return false;
    });
    return rowCount;
  }

  // invariant: Markdown presentation resolves through one stylesheet (src/modules/markdown/markdown.invariants.md)
  protected visitBlock(
    block: BlockRecord,
    blockIndex: number,
    width: number,
    emit: EmitRow,
  ): boolean {
    const stylesheet = MarkdownStylesheet.Class;
    const panePaddingText = stylesheet.panePaddingText;
    const innerWidth = Math.max(1, width - stylesheet.panePadding.right);
    switch (block.kind) {
      case 'code':
        return this.visitCode(block, blockIndex, width, emit);
      case 'blockquote': {
        const quotePrefix =
          panePaddingText + stylesheet.vocabulary.quoteBarPrefix;
        return this.visitWrapped(block, blockIndex, innerWidth, emit, {
          firstPrefix: quotePrefix,
          continuationPrefix: quotePrefix,
          suffix: '',
          role: 'quote',
          breakProfile: 'prose',
          fillWidth: false,
        });
      }
      case 'table':
        return false;
      case 'hr': {
        const ruleWidth = Math.max(
          0,
          width - panePaddingText.length - stylesheet.panePadding.right,
        );
        return emit(
          block,
          blockIndex,
          0,
          0,
          '',
          '',
          'rule',
          panePaddingText + stylesheet.vocabulary.ruleGlyph.repeat(ruleWidth),
        );
      }
      case 'listitem': {
        const indentation = stylesheet.listIndentText(block.level);
        const marker = block.marker ?? stylesheet.vocabulary.listMarkerFallback;
        const firstPrefix = `${panePaddingText}${indentation}${marker} `;
        return this.visitWrapped(block, blockIndex, innerWidth, emit, {
          firstPrefix,
          continuationPrefix: ' '.repeat(firstPrefix.length),
          suffix: '',
          role: 'content',
          breakProfile: 'prose',
          fillWidth: false,
        });
      }
      default:
        return this.visitWrapped(block, blockIndex, innerWidth, emit, {
          firstPrefix: panePaddingText,
          continuationPrefix: panePaddingText,
          suffix: '',
          role: 'content',
          breakProfile: 'prose',
          fillWidth: false,
        });
    }
  }

  protected visitCode(
    block: BlockRecord,
    blockIndex: number,
    width: number,
    emit: EmitRow,
  ): boolean {
    const stylesheet = MarkdownStylesheet.Class;
    const panePaddingText = stylesheet.panePaddingText;
    const frame = stylesheet.vocabulary.codeFrame;
    const frameWidth = Math.max(
      2,
      width - panePaddingText.length - stylesheet.panePadding.right,
    );
    const label = block.language ? ` ${block.language} ` : '';
    const topFill = Math.max(0, frameWidth - 2 - label.length);
    if (
      emit(
        block,
        blockIndex,
        0,
        0,
        '',
        '',
        'codeBorder',
        `${panePaddingText}${frame.topLeft}${label}${frame.horizontal.repeat(topFill)}${frame.topRight}`.slice(
          0,
          width,
        ),
      )
    ) {
      return true;
    }
    const framePrefix = `${panePaddingText}${frame.vertical} `;
    if (
      this.visitWrapped(
        block,
        blockIndex,
        Math.max(1, width - stylesheet.panePadding.right),
        emit,
        {
          firstPrefix: framePrefix,
          continuationPrefix: framePrefix,
          suffix: ` ${frame.vertical}`,
          role: 'codeContent',
          breakProfile: 'code',
          fillWidth: true,
        },
      )
    )
      return true;
    return emit(
      block,
      blockIndex,
      0,
      0,
      '',
      '',
      'codeBorder',
      `${panePaddingText}${frame.bottomLeft}${frame.horizontal.repeat(Math.max(0, frameWidth - 2))}${frame.bottomRight}`.slice(
        0,
        width,
      ),
    );
  }

  // invariant: Wrapped surfaces share one break generator (project.invariants.md)
  protected visitWrapped(
    block: BlockRecord,
    blockIndex: number,
    availableWidth: number,
    emit: EmitRow,
    options: WrappedVisitOptions,
  ): boolean {
    const contentWidth = Math.max(
      1,
      availableWidth -
        TextCoordinates.Class.lineWidth(options.firstPrefix) -
        TextCoordinates.Class.lineWidth(options.suffix),
    );
    let lineStart = 0;
    let isFirstLine = true;

    while (lineStart <= block.text.length) {
      const newline = block.text.indexOf('\n', lineStart);
      const physicalEnd = newline < 0 ? block.text.length : newline;
      if (
        this.visitWrappedLine(
          block,
          blockIndex,
          lineStart,
          physicalEnd,
          contentWidth,
          isFirstLine,
          emit,
          options,
        )
      ) {
        return true;
      }
      isFirstLine = false;
      if (newline < 0) break;
      lineStart = newline + 1;
    }
    return false;
  }

  protected visitWrappedLine(
    block: BlockRecord,
    blockIndex: number,
    lineStart: number,
    physicalEnd: number,
    contentWidth: number,
    isFirstLine: boolean,
    emit: EmitRow,
    options: WrappedVisitOptions,
  ): boolean {
    const rowSuffix = (segmentWidth: number): string =>
      options.fillWidth
        ? ' '.repeat(Math.max(0, contentWidth - segmentWidth)) + options.suffix
        : options.suffix;

    if (physicalEnd === lineStart) {
      return emit(
        block,
        blockIndex,
        lineStart,
        lineStart,
        isFirstLine ? options.firstPrefix : options.continuationPrefix,
        rowSuffix(0),
        options.role,
      );
    }

    const lineText = block.text.slice(lineStart, physicalEnd);
    const graphemes = TextCoordinates.Class.graphemes(lineText);
    const utf16Offsets: number[] = new Array(graphemes.length + 1);
    utf16Offsets[0] = 0;
    for (
      let graphemeIndex = 0;
      graphemeIndex < graphemes.length;
      graphemeIndex++
    ) {
      utf16Offsets[graphemeIndex + 1] =
        utf16Offsets[graphemeIndex]! + graphemes[graphemeIndex]!.length;
    }

    let segmentStart = 0;
    let isFirstSegment = isFirstLine;
    while (segmentStart < graphemes.length) {
      let segmentEnd = segmentStart;
      let segmentWidth = 0;
      while (segmentEnd < graphemes.length) {
        const graphemeWidth = TextCoordinates.Class.lineWidth(
          graphemes[segmentEnd]!,
        );
        if (
          segmentEnd > segmentStart &&
          segmentWidth + graphemeWidth > contentWidth
        ) {
          break;
        }
        segmentWidth += graphemeWidth;
        segmentEnd++;
      }
      if (segmentEnd < graphemes.length) {
        const preferredBreak =
          WrapBreakOpportunity.Class.previousBreakOpportunity(
            graphemes,
            segmentStart,
            segmentEnd,
            options.breakProfile,
          );
        if (preferredBreak > segmentStart && preferredBreak < segmentEnd) {
          segmentEnd = preferredBreak;
          segmentWidth = 0;
          for (
            let graphemeIndex = segmentStart;
            graphemeIndex < segmentEnd;
            graphemeIndex++
          ) {
            segmentWidth += TextCoordinates.Class.lineWidth(
              graphemes[graphemeIndex]!,
            );
          }
        }
      }
      if (
        emit(
          block,
          blockIndex,
          lineStart + utf16Offsets[segmentStart]!,
          lineStart + utf16Offsets[segmentEnd]!,
          isFirstSegment ? options.firstPrefix : options.continuationPrefix,
          rowSuffix(segmentWidth),
          options.role,
        )
      ) {
        return true;
      }
      isFirstSegment = false;
      segmentStart = segmentEnd;
      while (
        segmentStart < graphemes.length &&
        WrapBreakOpportunity.Class.breakKindBetween(
          graphemes[segmentStart]!,
          undefined,
          options.breakProfile,
        ) === 'whitespace'
      ) {
        segmentStart++;
      }
    }
    return false;
  }

  protected appendVisibleTableRows(
    rows: PreviewRow[],
    block: BlockRecord,
    blockIndex: number,
    width: number,
    firstLocalRow: number,
    endLocalRow: number,
    tableBorders: TableBorderGlyphSet,
  ): void {
    // invariant: Markdown tables align by display cells (src/modules/markdown/markdown.invariants.md)
    const table = block.table;
    if (!table || table.rows.length === 0) return;
    const panePadding = MarkdownStylesheet.Class.panePadding;
    const contentWidths = this.tableContentWidths(
      Math.max(1, width - panePadding.left - panePadding.right),
      table.alignments.length,
    );

    for (
      let localRowIndex = firstLocalRow;
      localRowIndex < endLocalRow;
      localRowIndex++
    ) {
      if (localRowIndex === 1) {
        rows.push(
          this.tableSeparatorRow(
            block,
            blockIndex,
            contentWidths,
            tableBorders,
          ),
        );
        continue;
      }
      const tableRowIndex = localRowIndex === 0 ? 0 : localRowIndex - 1;
      const tableRow = table.rows[tableRowIndex];
      if (!tableRow) continue;
      rows.push(
        this.tableContentRow(
          block,
          blockIndex,
          tableRow,
          tableRowIndex,
          table.alignments,
          contentWidths,
          tableBorders,
        ),
      );
    }
  }

  protected tableContentWidths(width: number, columnCount: number): number[] {
    if (columnCount <= 0) return [];
    const fixedBorderAndPaddingWidth = columnCount * 3 + 1;
    const distributableWidth = Math.max(
      columnCount,
      width - fixedBorderAndPaddingWidth,
    );
    const baseContentWidth = Math.floor(distributableWidth / columnCount);
    const extraColumns = distributableWidth % columnCount;
    return Array.from(
      { length: columnCount },
      (_unused, columnIndex) =>
        baseContentWidth + (columnIndex < extraColumns ? 1 : 0),
    );
  }

  protected tableContentRow(
    block: BlockRecord,
    blockIndex: number,
    cells: readonly TableCellRecord[],
    tableRowIndex: number,
    alignments: readonly TableColumnAlignment[],
    contentWidths: readonly number[],
    tableBorders: TableBorderGlyphSet,
  ): PreviewRow {
    const panePaddingText = MarkdownStylesheet.Class.panePaddingText;
    let overrideText = panePaddingText + tableBorders.vertical;
    let nextCellColumn = panePaddingText.length + 1;
    const previewCells: PreviewTableCell[] = [];

    for (
      let columnIndex = 0;
      columnIndex < contentWidths.length;
      columnIndex++
    ) {
      const contentWidth = contentWidths[columnIndex]!;
      const cell = cells[columnIndex]!;
      const visibleText = TextCoordinates.Class.displayColumnWindow(
        cell.text,
        0,
        contentWidth,
      );
      const unusedWidth = Math.max(
        0,
        contentWidth - TextCoordinates.Class.lineWidth(visibleText),
      );
      const alignment = alignments[columnIndex] ?? 'left';
      const alignmentPadding = this.tableAlignmentPadding(
        alignment,
        unusedWidth,
      );
      const leadingPadding = ` ${' '.repeat(alignmentPadding.left)}`;
      const trailingPadding = `${' '.repeat(alignmentPadding.right)} `;
      const textStartDisplayColumn =
        nextCellColumn + TextCoordinates.Class.lineWidth(leadingPadding);

      previewCells.push({
        cell,
        cellIndex: columnIndex,
        visibleText,
        leadingPadding,
        trailingPadding,
        textStartDisplayColumn,
      });
      overrideText +=
        leadingPadding + visibleText + trailingPadding + tableBorders.vertical;
      nextCellColumn += contentWidth + 3;
    }

    return {
      block,
      blockIndex,
      textStart: 0,
      textEnd: 0,
      prefix: '',
      suffix: '',
      role: tableRowIndex === 0 ? 'tableHeader' : 'tableBody',
      overrideText,
      tableRowIndex,
      tableCells: previewCells,
      tableBorders,
    };
  }

  protected tableAlignmentPadding(
    alignment: TableColumnAlignment,
    unusedWidth: number,
  ): { left: number; right: number } {
    if (alignment === 'right') return { left: unusedWidth, right: 0 };
    if (alignment === 'center') {
      const left = Math.floor(unusedWidth / 2);
      return { left, right: unusedWidth - left };
    }
    return { left: 0, right: unusedWidth };
  }

  protected tableSeparatorRow(
    block: BlockRecord,
    blockIndex: number,
    contentWidths: readonly number[],
    tableBorders: TableBorderGlyphSet,
  ): PreviewRow {
    const segments = contentWidths.map((contentWidth) =>
      tableBorders.horizontal.repeat(contentWidth + 2),
    );
    return {
      block,
      blockIndex,
      textStart: 0,
      textEnd: 0,
      prefix: '',
      suffix: '',
      role: 'tableSeparator',
      overrideText:
        MarkdownStylesheet.Class.panePaddingText +
        tableBorders.leftJunction +
        segments.join(tableBorders.intersection) +
        tableBorders.rightJunction,
      tableBorders,
    };
  }

  protected statusRow(text: string): PreviewRow {
    return {
      block: null,
      blockIndex: -1,
      textStart: 0,
      textEnd: 0,
      prefix: '',
      suffix: '',
      role: 'status',
      overrideText: MarkdownStylesheet.Class.panePaddingText + text,
    };
  }
}

export namespace MarkdownPreview {
  export const $Class = Static($MarkdownPreview);
  export let Class = Reactive($Class);
  export type Model = InstanceType<typeof Class>;
  export type Instance = typeof Class.Instance;
}

export interface RenderTarget {
  requestRender(): void;
}

export type PreviewRowRole =
  | 'content'
  | 'codeBorder'
  | 'codeContent'
  | 'quote'
  | 'tableHeader'
  | 'tableBody'
  | 'tableSeparator'
  | 'rule'
  | 'spacer'
  | 'status';

/** Ephemeral flyweight row. Only rows in the requested viewport are instantiated. */
export interface PreviewRow {
  block: BlockRecord | null;
  blockIndex: number;
  textStart: number;
  textEnd: number;
  prefix: string;
  suffix: string;
  role: PreviewRowRole;
  overrideText?: string;
  tableRowIndex?: number;
  tableCells?: readonly PreviewTableCell[];
  tableBorders?: TableBorderGlyphSet;
}

export interface PreviewTableCell {
  cell: TableCellRecord;
  cellIndex: number;
  visibleText: string;
  leadingPadding: string;
  trailingPadding: string;
  textStartDisplayColumn: number;
}

interface WrappedVisitOptions {
  readonly firstPrefix: string;
  readonly continuationPrefix: string;
  /** Painted after the row text; with fillWidth the row is space-padded to contentWidth first
   *  so a right frame edge stays on one column. */
  readonly suffix: string;
  readonly role: PreviewRowRole;
  readonly breakProfile: WrapBreakProfile;
  readonly fillWidth: boolean;
}

type EmitRow = (
  block: BlockRecord | null,
  blockIndex: number,
  textStart: number,
  textEnd: number,
  prefix: string,
  suffix: string,
  role: PreviewRowRole,
  overrideText?: string,
) => boolean;
